[package]
name = "actaeon"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openssl = "0.10.35"
blake3 = "1.0.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4.14"
toml = "0.5"
uuid = { version = "0.8", features = ["serde", "v4"] }
thiserror = "1.0.26"
